version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: 'postgres:12-alpine'
    restart: always
    environment:
        DATABASE_URL: postgres://postgres@db/postgres
        POSTGRES_PASSWORD: postgres